---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false


library(tidyverse)
library(here)
library(fs)
# library(snakecase) # inside this package is a function that can help turn column names into "snakecase" -> used in the read function we made
source(here("R/functions.R"))
```


## Importing new data

name_repair = to_snake_case = helps convert the column names to snakecase (better for readability)

n_max is used to tell how many rows to import. might be useful for larger dataset to get a view of the data
```{r}
#| eval: false
# Code chunk

here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Exercise: Reading other files

```{r}
#| eval: false
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    # n_max = 100
  )

here("data-raw/nurses-stress/stress/6B/6B_1587585327/HR.csv.gz") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


## Making a function to add numbers

```{r}
#' Add two numbers together
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```


## create a function to import data

```{r}
#| eval: false
#' Read in nurses' stress data file
#'
#' @param file_path this is the oath to a data file
#' @param max_rows this is the number of rows shown in the output. Default 100
#'
#'
#' @returns outputs a dataframe/tibble
read <- function(file_path, max_rows = 100) {
  data <- file_path %>%
    readr::read_csv( # to explicitly tell R studio to use read_csv from readr package
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = max_rows
    )
  return(data)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") %>%
  read()
```

```{r}
# Outputs only 100 rows (default)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read()

# Outputs only 1000 rows
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read(max_rows = 1000)

# Outputs all rows (`Inf` means infinity)
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") %>%
  read(max_rows = Inf)
```


## using map()

```{r}
hr_files <- here("data-raw/nurses-stress/") %>%
  dir_ls(regexp = "HR.csv.gz", recurse = TRUE)

hr_files

hr_data <- hr_files %>%
  map(read) %>% # here we use the read function we made but without BRACKETS ()
  list_rbind(names_to = "file_path_id") # use rbind because columns names are the same for the different files


hr_data
```
